name: Update Counter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust as needed)

jobs:
  update-counter:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the workflow has permissions to update files

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set to your project's Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Counter Update Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
        run: node script.js
